---
apiVersion: batch/v1
kind: Job
metadata:
  name: namf-pack-register-job
spec:
  template:
    metadata:
      labels:
        tef-l2-oracle-network-access: "true"
        tef-l3-service-network-access: "true"
    spec:
      serviceAccountName: altaia-namf-app-sa
      securityContext:
        runAsGroup: 1982
        runAsUser: 1982
        supplementalGroups:
          - 1982
      containers:
        - name: namf-install-catalogs
          image: "quay.apps.mgmt.tdigital-vivo.com.br/altaia_full/namf-sol/altaia-vivo/automation-vivo:1.0.4b"
          imagePullPolicy: Always
          command:
            - python3
            - -u
            - /opt/alticelabs/namf/pack-register/pack-register-upload.py
          envFrom:
            - configMapRef:
                name: namf-pack-register-conf
            - secretRef:
                name: secret-namf-pack-register
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 5000
  backoffLimit: 9999