#!/usr/bin/env python

__doc__ = \
    '''
    Enrichment Operator
'''

__version__ = '0.1'

__authors__ = [
    "Version 0.1: Vanessa Ramos <vanessa-c-ramos@alticelabs.com>"
]

# import vendorConvert
import gzip
from csv import reader
import csv
import importlib
import os
import re
import io
import fnmatch
from datetime import datetime

# Local libraries
BaseOperator = importlib.import_module("shelf.collectorprocess.operators.BaseOperator").BaseOperator
FamilyObject = importlib.import_module("shelf.collectorprocess.operators.FamilyObject").FamilyObject
logger = importlib.import_module("shelf.collectorprocess.logger").logger


class Operator(BaseOperator):

    # Class Constructor
    def __init__(self, operationParams, baseObject={}):
        BaseOperator.__init__(self, operationParams, baseObject=baseObject)
        self.__endpoints = []
        self.__enrichment = False
        self._polls = dict()
        self._lastReportedTimestamp = ""

        self.callee_number_pattern = re.compile(r'(tel:|sip:)(.*?)[;@]')


    def process(self, familyObj=FamilyObject(), baseObject={}):
        filesToProcess = familyObj.getFiles()
        familyObj.clearDocuments()

        if not self.__endpoints:
            self.__endpoints = self.processEnrichFiles()
            if self.__endpoints:
                self.__enrichment = True
            else:
                logger.warning("Enrichment File Was Not Found!!!")

        for file_path in filesToProcess:

            # Get file's name
            file_name = os.path.basename(file_path)
            familyObj.fileName = file_name

            try:
                # Open file for writing
                if os.path.splitext(file_name)[1] == ".gz":
                    f = io.BufferedReader(gzip.open(file_path))
                else:
                    f = open(file_path, 'r')
            except IOError:
                logger.warning("Could not open sample file '{}' in read mode: ".format(file_name))
                continue

            familyObj.unitID = "CDRS_SBC"

            stop_header = ['STOP','GATEWAYNAME','ACCOUNTINGID','STARTTIMEINSYSTEMTICKS','NODETIMEZONE','STARTTIMEDATE','STARTTIMETIME','TIMEELAPSEDFROMRECEIPTOFSETUPMESSAGETOPOLICYSERVERSOFTSWITCHRESPONSE','TIMEELAPSEDFROMRECEIPTOFSETUPMESSAGETORECEIPTOFALERTINGPROCPROG','TIMEELAPSEDFROMRECEIPTOFSETUPMESSAGETOSERVICEESTABLISHED','DISCONNECTTIMEDATE','DISCONNECTTIMETIME','TIMEELAPSEDFROMRECEIPTOFDISCONNECTTOCOMPLETIONOFCALL','CALLSERVICEDURATION','CALLDISCONNECTREASON','SERVICEDELIVERED','CALLDIRECTION','SERVICEPROVIDER','TRANSITNETWORKSELECTIONCODE','CALLINGNUMBER','CALLEDNUMBER','EXTRACALLEDADDRESSDIGITS','NUMBEROFCALLEDNUMTRANSLATIONSDONEBYTHISNODE','CALLEDNUMBERBEFORETRANSLATION1','TRANSLATIONTYPE1','CALLEDNUMBERBEFORETRANSLATION2','TRANSLATIONTYPE2','BILLINGNUMBER','ROUTELABEL','ROUTEATTEMPTNUMBER','ROUTESELECTED','EGRESSLOCALGATEWAYSIGNALINGIPADDRESS','EGRESSREMOTEGATEWAYSIGNALINGIPADDRESS','INGRESSTRUNKGROUPNAME','INGRESSPSTNCIRCUITENDPOINT','INGRESSIPCIRCUITENDPOINT','EGRESSPSTNCIRCUITENDPOINT','EGRESSIPCIRCUITENDPOINT','INGRESSNUMBEROFAUDIOBYTESSENT','INGRESSNUMBEROFAUDIOPACKETSSENT','INGRESSNUMBEROFAUDIOBYTESRECEIVED','INGRESSNUMBEROFAUDIOPACKETSRECEIVED','ORIGINATINGLINEINFORMATIONOLIP','JURISDICTIONINFORMATIONPARAMETER','CARRIERCODE','CALLGROUPID','SCRIPTLOGDATA','TIMEELAPSEDFROMRECEIPTOFSETUPMESSAGETORECEIPTOFEXITMESSAGE','TIMEELAPSEDFROMRECEIPTOFSETUPMESSAGETOGENERATIONOFEXITMESSAGE','CALLINGPARTYNATUREOFADDRESS','CALLEDPARTYNATUREOFADDRESS','INGRESSPROTOCOLVARIANTSPECIFICDATA','INGRESSSIGNALINGTYPE','EGRESSSIGNALINGTYPE','INGRESSFARENDSWITCHTYPE','EGRESSFARENDSWITCHTYPE','FARENDINGRESSTGCARRIERCODE','FARENDEGRESSTGCARRIERCODE','CALLINGPARTYCATEGORY','DIALEDNUMBER','CARRIERSELECTIONINFORMATION','CALLEDNUMBERNUMBERINGPLAN','GENERICADDRESSPARAMETER','DISCONNECTINITIATOR','INGRESSNUMBEROFPACKETSRECORDEDASLOST','INGRESSINTERARRIVALPACKETJITTER','INGRESSLASTMEASUREMENTFORLATENCY','EGRESSTRUNKGROUPNAME','EGRESSPROTOCOLVARIANTSPECIFICDATA','INCOMINGCALLINGNUMBER','AMACALLTYPE','MESSAGEBILLINGINDEXMBI','ORIGINATINGLATA','ROUTEINDEXUSED','CALLINGPARTYNUMBERPRESENTATIONRESTRICTION','INCOMINGISUPCHARGENUMBER','INCOMINGISUPCHARGENUMBERNOA','DIALEDNUMBERNOA','INGRESSCODECTYPE','EGRESSCODECTYPE','INGRESSRTPPACKETIZATIONTIME','SBCCALLID','ORIGINATORECHOCANCELLATION','TERMINATORECHOCANCELLATION','CHARGEFLAG','AMASERVICELOGICIDENTIFICATION','AMABAFMODULE','AMASETHEXABINDICATION','SERVICEFEATUREID','FEPARAMETER','SATELLITEINDICATOR','PSXBILLINGINFORMATION','ORIGINATINGTDMTRUNKGROUPTYPE','TERMINATINGTDMTRUNKGROUPTYPE','INGRESSTRUNKMEMBERNUMBER','EGRESSTRUNKGROUPID','EGRESSSWITCHID','INGRESSLOCALATMADDRESS','INGRESSREMOTEATMADDRESS','EGRESSLOCALATMADDRESS','EGRESSREMOTEATMADDRESS','POLICYRESPONSECALLTYPE','OUTGOINGROUTEIDENTIFICATION','OUTGOINGMESSAGEIDENTIFICATION','INCOMINGROUTEIDENTIFICATION','CALLINGNAME','CALLINGNAMETYPE','INCOMINGCALLINGPARTYNUMBERINGPLAN','OUTGOINGCALLINGPARTYNUMBERINGPLAN','CALLINGPARTYBUSINESSGROUPID','CALLEDPARTYBUSINESSGROUPID','CALLINGPARTYPUBLICPRESENCEDIRECTORYNUMBER','ELAPSEDTIMEFROMRECEIPTOFSETUPMESSAGETOLASTCALLROUTINGATTEMPT','BILLINGNUMBERNOA','INCOMINGCALLINGNUMBERNOA','EGRESSTRUNKMEMBERNUMBER','SELECTEDROUTETYPE','TELCORDIALONGDURATIONRECORDTYPE','TIMEELAPSEDFROMPREVIOUSRECORD','CUMULATIVEROUTEINDEX','CALLDISCONNECTREASONTRANSMITTEDTOINGRESS','CALLDISCONNECTREASONTRANSMITTEDTOEGRESS','ISDNPRICALLINGPARTYSUBADDRESS','OUTGOINGTRUNKGROUPNUMBERINEXM','INGRESSLOCALGATEWAYSIGNALINGIPADDRESS','INGRESSREMOTEGATEWAYSIGNALINGIPADDRESS','RECORDSEQUENCENUMBER','TRANSMISSIONMEDIUMREQUIREMENTTMR','INFORMATIONTRANSFERRATEITR','USERSERVICEINFORMATIONUSIUSERINFORMATIONLAYER1','UNRECOGNIZEDRAWISUPCALLINGPARTYCATEGORY','EGRESSRLTFEATURESPECIFICDATA','TWOBCHANNELTRANSFERFEATURESPECIFICDATA','CALLINGPARTYBUSINESSUNIT','CALLEDPARTYBUSINESSUNIT','REDIRECTIONFEATURESPECIFICDATA','INGRESSRLTFEATURESPECIFICDATA','PSXINDEX','PSXCONGESTIONLEVEL','PSXPROCESSINGTIME','SCRIPTNAME','INGRESSEXTERNALACCOUNTINGDATA','EGRESSEXTERNALACCOUNTINGDATA','EGRESSRTPPACKETIZATIONTIME','EGRESSNUMBEROFAUDIOBYTESSENT','EGRESSNUMBEROFAUDIOPACKETSSENT','EGRESSNUMBEROFAUDIOBYTESRECEIVED','EGRESSNUMBEROFAUDIOPACKETSRECEIVED','EGRESSNUMBEROFPACKETSRECORDEDASLOST','EGRESSINTERARRIVALPACKETJITTER','EGRESSLASTMEASUREMENTFORLATENCY','INGRESSMAXIMUMPACKETOUTAGE','EGRESSMAXIMUMPACKETOUTAGE','INGRESSPACKETPLAYOUTBUFFERQUALITY','EGRESSPACKETPLAYOUTBUFFERQUALITY','ANSWERSUPERVISIONTYPE','INGRESSSIPREFERANDREPLACESFEATURESPECIFICDATA','EGRESSSIPREFERANDREPLACESFEATURESPECIFICDATA','NETWORKTRANSFERFEATURESPECIFICDATA','CALLCONDITION','TOLLINDICATOR','GENERICNUMBERNUMBER','GENERICNUMBERPRESENTATIONRESTRICTIONINDICATOR','GENERICNUMBERNUMBERINGPLAN','GENERICNUMBERNATUREOFADDRESS','GENERICNUMBERTYPE','ORIGINATINGTRUNKTYPE','TERMINATINGTRUNKTYPE','REMOTESBCBILLINGINDICATOR','VPNCALLINGPRIVATEPRESENCENUMBER','VPNCALLINGPUBLICPRESENCENUMBER','EXTERNALFURNISHCHARGINGINFO','INGRESSPOLICINGDISCARDS','EGRESSPOLICINGDISCARDS','ANNOUNCEMENTID','SOURCEINFORMATION','PARTITIONID','NETWORKID','NCOS','INGRESSSRTP','EGRESSSRTP','ISDNACCESSINDICATORFROMTHEFORWARDCALLINDICATOR','CALLDISCONNECTLOCATION','CALLDISCONNECTLOCATIONTRANSMITTEDTOINGRESS','CALLDISCONNECTLOCATIONTRANSMITTEDTOEGRESS','NETWORKCALLREFERENCECALLIDENTITY','NETWORKCALLREFERENCESIGNALINGPOINTCODE','INGRESSISUPMIMEPROTOCOLVARIANTSPECIFICDATA','EGRESSISUPMIMEPROTOCOLVARIANTSPECIFICDATA','MODEMTONETYPE','MODEMTONESIGNALLEVEL','VIDEOCODECDATA','VIDEOCODECSTATISTICS','SVSCUSTOMER','SVSVENDORDEPRECATED','CALLTOTESTPSX','PSXOVERLAPROUTEREQUESTS','CALLSETUPDELAY','OVERLOADSTATUS','RESERVEDINGRESSBICCINFO','RESERVEDEGRESSBICCINFO','INGRESSDSPDATA','EGRESSDSPDATA','CALLRECORDEDINDICATOR','CALLRECORDEDRTPTXIPADDRESS','CALLRECORDEDRTPTXPORTNUMBER','CALLRECORDEDRTPRVIPADDRESS','CALLRECORDEDRTPRVPORTNUMBER','MLPPPRECEDENCELEVEL','RESERVEDMSRPSERVICETYPE','RESERVEDNPUKKSPECIALROUTINGINFORMATION','RESERVEDNPUKKCUSTOMERORCARRIERIDENTIFICATION','RESERVEDNPUKKSERVICETYPEIDENTIFIER','RESERVEDNPSSPSPECIALHANDLINGINFORMATION','RESERVEDNPSSPSERVICETYPEIDENTIFIER','RESERVEDTOTALITXCHARGEUNITS','GLOBALCHARGEREFERENCEGCR','RESERVEDIPCALLLIMITATINGRESSSIPPEER','RESERVEDIPCALLLIMITATINGRESSIPTG','RESERVEDIPBWLIMITATINGRESSIPTG','RESERVEDIPCALLLIMITATEGRESSSIPPEER','RESERVEDIPCALLLIMITATEGRESSIPTG','RESERVEDIPBWLIMITATEGRESSIPTG','RESERVEDPSXNAME','RESERVEDNO.OFPSXTRIED','INGRESSINBOUNDRFACTOR','INGRESSOUTBOUNDRFACTOR','EGRESSINBOUNDRFACTOR','EGRESSOUTBOUNDRFACTOR','MEDIASTREAMDATA','MEDIASTREAMSTATS','TRANSCODEINDICATOR','HDCODECRATE','REMOTEINGRESSAUDIORTCPLEARNEDMETRICS','REMOTEEGRESSAUDIORTCPLEARNEDMETRICS','RESERVEDFINALROUTELABEL','MTAINFORMATION','VBRCOMMONBILLINGDATA','VBRROUTEBILLINGDATA','ACCESSTRANSFERSPECIFICDATA','EMERGENCYINDICATOR','INGRESSDTLSSRTPDTLSSRTPSTATUSINFO','EGRESSDTLSSRTPDTLSSRTPSTATUSINFO','UEROAMINGSTATUS','ACCESSNETWORKCHARGINGINFORMATION','INGRESSSIGNALEDSESSIONBANDWIDTHINKBPS','INGRESSRXCOMPUTEDSESSIONBANDWIDTHINKBPS','INGRESSTXCOMPUTEDSESSIONBANDWIDTHINKBPS','INGRESSCONFIGUREDBANDWIDTHREDUCTIONFACTOR','INGRESSESTIMATEDBANDWIDTHREDUCTIONFACTOR','EGRESSSIGNALEDSESSIONBANDWIDTHINKBPS','EGRESSRXCOMPUTEDSESSIONBANDWIDTHINKBPS','EGRESSTXCOMPUTEDSESSIONBANDWIDTHINKBPS','EGRESSCONFIGUREDBANDWIDTHREDUCTIONFACTOR','EGRESSESTIMATEDBANDWIDTHREDUCTIONFACTOR','ADDITIONALMEDIASTREAMSTATISTICS','INGRESSZONENAME','EGRESSZONENAME','INGRESSZONEID','EGRESSZONEID','VIDEOCAC','INGRESSIPPREFIXFOUNDTGNAME','TRANSCODERESOURCETYPE','MRFINFORMATION','FORKINGCALLPARENTGCID','CALLRECORDER1RTPTXIPADDRESS','CALLRECORDER1RTPTXPORTNUMBER','CALLRECORDER1RTPRXIPADDRESS','CALLRECORDER1RTPRXPORTNUMBER','CALLRECORDER2RTPTXIPADDRESS','CALLRECORDER2RTPTXPORTNUMBER','CALLRECORDER2RTPRXIPADDRESS','CALLRECORDER2RTPRXPORTNUMBER','CALLRECORDER3RTPTXIPADDRESS','CALLRECORDER3RTPTXPORTNUMBER','CALLRECORDER3RTPRXIPADDRESS','CALLRECORDER3RTPRXPORTNUMBER','SOSBC','AUDIOSTREAMSTATISTICS','AUDIOSTREAMRTCPXRVOICEMETRICSTATISTICS','MEDIASTREAMSRTPSTATISTICS','DSPINSERTIONREJECTIONREASON','CALLESTABLISHEDTIME','OVERFLOWPACKETSCOUNT','INGRESSTRUNKGROUPFORPSXROUTING','T140INFORMATION','REMOTET140RTCPLEARNEDMETRICS','VTPINFORMATION','BEEPTONEINSERTED','DIRECTIONOFBEEPTONE','STARTTIMELOCAL','DISCONNECTTIMELOCAL','CALLESTABLISHEDTIMELOCAL','RESERVEDGUID','RESERVEDMEDIAIPSECINFORMATION']
            att_header = ['ATTEMPT','GATEWAYNAME','ACCOUNTINGID','STARTTIMEINSYSTEMTICKS','NODETIMEZONE','STARTTIMEDATE','STARTTIMETIME','TIMEELAPSEDFROMRECEIPTOFSETUPMESSAGETOPOLICYSERVERSOFTSWITCHRESPONSE','TIMEELAPSEDFROMRECEIPTOFSETUPMESSAGETORECEIPTOFALERTINGPROCPROG','DISCONNECTTIMETIME','TIMEELAPSEDFROMRECEIPTOFDISCONNECTTOCOMPLETIONOFCALL','CALLDISCONNECTREASON','SERVICEDELIVERED','CALLDIRECTION','SERVICEPROVIDER','TRANSITNETWORKSELECTIONCODE','CALLINGNUMBER','CALLEDNUMBER','EXTRACALLEDADDRESSDIGITS','NUMBEROFCALLEDNUMTRANSLATIONSDONEBYTHISNODE','CALLEDNUMBERBEFORETRANSLATION1','TRANSLATIONTYPE1','CALLEDNUMBERBEFORETRANSLATION2','TRANSLATIONTYPE2','BILLINGNUMBER','ROUTELABEL','ROUTEATTEMPTNUMBER','ROUTESELECTED','EGRESSLOCALGATEWAYSIGNALINGIPADDRESS','EGRESSREMOTEGATEWAYSIGNALINGIPADDRESS','INGRESSTRUNKGROUPNAME','INGRESSPSTNCIRCUITENDPOINT','INGRESSIPCIRCUITENDPOINT','EGRESSPSTNCIRCUITENDPOINT','EGRESSIPCIRCUITENDPOINT','ORIGINATINGLINEINFORMATIONOLIP','JURISDICTIONINFORMATIONPARAMETER','CARRIERCODE','CALLGROUPID','SCRIPTLOGDATA','TIMEELAPSEDFROMRECEIPTOFSETUPMESSAGETORECEIPTOFEXITMESSAGE','TIMEELAPSEDFROMRECEIPTOFSETUPMESSAGETOGENERATIONOFEXITMESSAGE','CALLINGPARTYNATUREOFADDRESS','CALLEDPARTYNATUREOFADDRESS','INGRESSPROTOCOLVARIANTSPECIFICDATA','INGRESSSIGNALINGTYPE','EGRESSSIGNALINGTYPE','INGRESSFARENDSWITCHTYPE','EGRESSFARENDSWITCHTYPE','FARENDINGRESSTGCARRIERCODE','FARENDEGRESSTGCARRIERCODE','CALLINGPARTYCATEGORY','DIALEDNUMBER','CARRIERSELECTIONINFORMATION','CALLEDNUMBERNUMBERINGPLAN','GENERICADDRESSPARAMETER','DISCONNECTINITIATOR','EGRESSTRUNKGROUPNAME','EGRESSPROTOCOLVARIANTSPECIFICDATA','INCOMINGCALLINGNUMBER','AMACALLTYPE','MESSAGEBILLINGINDEXMBI','ORIGINATINGLATA','ROUTEINDEXUSED','CALLINGPARTYNUMBERPRESENTATIONRESTRICTION','INCOMINGISUPCHARGENUMBER','INCOMINGISUPCHARGENUMBERNOA','DIALEDNUMBERNOA','INGRESSCODECTYPE','EGRESSCODECTYPE','INGRESSRTPPACKETIZATIONTIME','SBCCALLID','TERMINATEDWITHSCRIPTEXECUTION','ORIGINATORECHOCANCELLATION','TERMINATORECHOCANCELLATION','CHARGEFLAG','AMASERVICELOGICIDENTIFICATION','AMABAFMODULE','AMASETHEXABINDICATION','SERVICEFEATUREID','FEPARAMETER','SATELLITEINDICATOR','PSXBILLINGINFORMATION','ORIGINATINGTDMTRUNKGROUPTYPE','TERMINATINGTDMTRUNKGROUPTYPE','INGRESSTRUNKMEMBERNUMBER','EGRESSTRUNKGROUPID','EGRESSSWITCHID','INGRESSLOCALATMADDRESS','INGRESSREMOTEATMADDRESS','EGRESSLOCALATMADDRESS','EGRESSREMOTEATMADDRESS','POLICYRESPONSECALLTYPE','OUTGOINGROUTEIDENTIFICATION','OUTGOINGMESSAGEIDENTIFICATION','INCOMINGROUTEIDENTIFICATION','CALLINGNAME','CALLINGNAMETYPE','INCOMINGCALLINGPARTYNUMBERINGPLAN','OUTGOINGCALLINGPARTYNUMBERINGPLAN','CALLINGPARTYBUSINESSGROUPID','CALLEDPARTYBUSINESSGROUPID','CALLINGPARTYPUBLICPRESENCEDIRECTORYNUMBER','ELAPSEDTIMEFROMRECEIPTOFSETUPMESSAGETOLASTCALLROUTINGATTEMPT','DISCONNECTTIMEDATE','BILLINGNUMBERNOA','INCOMINGCALLINGNUMBERNOA','EGRESSTRUNKMEMBERNUMBER','SELECTEDROUTETYPE','CUMULATIVEROUTEINDEX','CALLDISCONNECTREASONTRANSMITTEDTOINGRESS','CALLDISCONNECTREASONTRANSMITTEDTOEGRESS','ISDNPRICALLINGPARTYSUBADDRESS','OUTGOINGTRUNKGROUPNUMBERINEXM','INGRESSLOCALGATEWAYSIGNALINGIPADDRESS','INGRESSREMOTEGATEWAYSIGNALINGIPADDRESS','RECORDSEQUENCENUMBER','TRANSMISSIONMEDIUMREQUIREMENTTMR','INFORMATIONTRANSFERRATEITR','USERSERVICEINFORMATIONUSIUSERINFORMATIONLAYER1','UNRECOGNIZEDRAWISUPCALLINGPARTYCATEGORY','EGRESSRLTFEATURESPECIFICDATA','TWOBCHANNELTRANSFERFEATURESPECIFICDATA','CALLINGPARTYBUSINESSUNIT','CALLEDPARTYBUSINESSUNIT','REDIRECTIONFEATURESPECIFICDATA','INGRESSRLTFEATURESPECIFICDATA','PSXINDEX','PSXCONGESTIONLEVEL','PSXPROCESSINGTIME','SCRIPTNAME','INGRESSEXTERNALACCOUNTINGDATA','EGRESSEXTERNALACCOUNTINGDATA','EGRESSRTPPACKETIZATIONTIME','ANSWERSUPERVISIONTYPE','INGRESSSIPREFERANDREPLACESFEATURESPECIFICDATA','EGRESSSIPREFERANDREPLACESFEATURESPECIFICDATA','NETWORKTRANSFERFEATURESPECIFICDATA','CALLCONDITION','TOLLINDICATOR','GENERICNUMBERNUMBER','GENERICNUMBERPRESENTATIONRESTRICTIONINDICATOR','GENERICNUMBERNUMBERINGPLAN','GENERICNUMBERNATUREOFADDRESS','GENERICNUMBERTYPE','FINALATTEMPTINDICATOR','ORIGINATINGTRUNKTYPE','TERMINATINGTRUNKTYPE','REMOTESBCBILLINGINDICATOR','EXTRADISCONNECTREASON','VPNCALLINGPRIVATEPRESENCENUMBER','VPNCALLINGPUBLICPRESENCENUMBER','EXTERNALFURNISHCHARGINGINFO','ANNOUNCEMENTID','SOURCEINFORMATION','PARTITIONID','NETWORKID','NCOS','ISDNACCESSINDICATORFROMTHEFORWARDCALLINDICATOR','CALLDISCONNECTLOCATION','CALLDISCONNECTLOCATIONTRANSMITTEDTOINGRESS','CALLDISCONNECTLOCATIONTRANSMITTEDTOEGRESS','NETWORKCALLREFERENCECALLIDENTITY','NETWORKCALLREFERENCESIGNALINGPOINTCODE','INGRESSISUPMIMEPROTOCOLVARIANTSPECIFICDATA','EGRESSISUPMIMEPROTOCOLVARIANTSPECIFICDATA','VIDEOCODECDATA','SVSCUSTOMER','SVSVENDORDEPRECATED','CALLTOTESTPSX','PSXOVERLAPROUTEREQUESTS','CALLSETUPDELAY','OVERLOADSTATUS','RESERVEDINGRESSBICCINFO','RESERVEDEGRESSBICCINFO','MLPPPRECEDENCELEVEL','RESERVEDMSRPSERVICETYPE','RESERVEDNPUKKSPECIALROUTINGINFORMATION','RESERVEDNPUKKCUSTOMERORCARRIERIDENTIFICATION','RESERVEDNPUKKSERVICETYPEIDENTIFIER','RESERVEDNPSSPSPECIALHANDLINGINFORMATION','RESERVEDNPSSPSERVICETYPEIDENTIFIER','RESERVEDONISTR','RESERVEDSUPPRESSONI','GLOBALCHARGEREFERENCEGCR','RESERVED3XXCONTACTINFORMATION','RESERVEDPSXNAME','RESERVEDNO.OFPSXTRIED','RESERVEDFINALROUTELABEL','MTAINFORMATION','VBRCOMMONBILLINGDATA','VBRROUTEBILLINGDATA','ACCESSTRANSFERSPECIFICDATA','EMERGENCYINDICATOR','UEROAMINGSTATUS','ACCESSNETWORKCHARGINGINFORMATION','INGRESSZONENAME','EGRESSZONENAME','INGRESSZONEID','EGRESSZONEID','INGRESSIPPREFIXFOUNDTGNAME','ADDITIONALMEDIASTREAMSTATISTICS','FORKINGCALLPARENTGCID','SOSBC','DSPINSERTION/REJECTIONREASON','CALLESTABLISHEDTIME','INGRESSTRUNKGROUPFORPSXROUTING','STARTTIMELOCAL','DISCONNECTTIMELOCAL','CALLESTABLISHEDTIMELOCAL','RESERVEDGUID','CACFAILINFO']


            n_line = 0
            try:

                for line in reader(f, delimiter=","):

                    n_line += 1

                    if line[0] != 'STOP' and line[0] != 'ATTEMPT':
                        continue

                    else:
                        if line[0] == 'STOP':

                            document = dict(zip(stop_header, line))

                            mediastats = document['MEDIASTREAMSTATS']

                            mediastats = mediastats.split(',')

                            num_streams = int(mediastats[0])

                            document['NUMBEROFSTREAMS'] = num_streams

                            i=0
                            # Ler as tres primeiras streams
                            while i <3 and i< num_streams:
                                i=i+1

                                stream_header=['MEDIATYPE'+str(i),'STREAMINDEX'+str(i),'INGRESSPACKETSENT'+str(i),'INGRESSPACKETRECEIVED'+str(i),'INGRESSOCTETSENT'+str(i),'INGRESSOCTETRECEIVED'+str(i),'INGRESSPACKETLOST'+str(i),'INGRESSPACKETDISCARDED'+str(i),'EGRESSPACKETSENT'+str(i),'EGRESSPACKETRECEIVED'+str(i),'EGRESSOCTETSENT'+str(i),'EGRESSOCTETRECEIVED'+str(i),'EGRESSPACKETLOST'+str(i),'EGRESSPACKETDISCARDED'+str(i)]

                                stream_content=mediastats[i*1:i*len(stream_header)+1]

                                document2 = dict(zip(stream_header, stream_content))

                                document=dict(document.items() + document2.items())

                        # Tem de ser um evento de attempt

                        else:
                            document = dict(zip(att_header, line))

                            # Obter Causa de falha da chamada
                            document["STATUSMESSAGEFORCALLRELEASE"]= document['INGRESSPROTOCOLVARIANTSPECIFICDATA'].split(',')[18]


                        if self.__enrichment:
                            document['TYPEOFCALL']=self.enrichment(document['INGRESSTRUNKGROUPNAME'], document['EGRESSTRUNKGROUPNAME'])

                        # Obter numero de telefone
                        # Usar sub campo do IngressProtocolVariantSpecificData
                        ing_prot_var_spec_data = document['INGRESSPROTOCOLVARIANTSPECIFICDATA'].split(",")

                        URI = ing_prot_var_spec_data[2]
                        document["SIPURIPAI"]=URI
                        if URI:
                            phone = URI.split(':')[1].split('@')[0]
                            # print document['INGRESSPROTOCOLVARIANTSPECIFICDATA']+"<-TELEPHONE->"+phone
                            document["CALLERNUMBERSIPURIPAI"]=phone

                        callee_number_info = ing_prot_var_spec_data[8] if len(ing_prot_var_spec_data) >= 9 else None
                        if callee_number_info:  # != '' and is not None
                            match = self.callee_number_pattern.search(callee_number_info)
                            if match:
                                document['CALLEENUMBER'] = match.group(2)

                        # Remover coluna que ta no ficheiro e nao guardamos em BD pois colocamos o EventType
                        document.pop(line[0])

                        if document["INCOMINGCALLINGNUMBER"].startswith('351'):
                            document["INCOMINGCALLINGNUMBER"]='+'+document["INCOMINGCALLINGNUMBER"]

                        document["EVENTTYPE"]=line[0]
                        data_tmp=document["STARTTIMEDATE"]+' '+document["STARTTIMETIME"].split('.')[0]

                        data_time = datetime.strptime(data_tmp, "%m/%d/%Y %H:%M:%S")
                        data_time = datetime.strftime(data_time,"%Y-%m-%d %H:%M:%S")

                        data_disc=document["DISCONNECTTIMEDATE"]+' '+document["DISCONNECTTIMETIME"].split('.')[0]
                        data_disc = datetime.strptime(data_disc, "%m/%d/%Y %H:%M:%S")
                        data_disc = datetime.strftime(data_disc,"%Y-%m-%d %H:%M:%S")

                        document["STARTTIMEDATETIME"]=data_time

                        document["DISCONNECTTIMEDATETIME"]=data_disc

                        # Imprimir PKs
                        # print line[0]+'<->' + document["ACCOUNTINGID"]+'<->' + document["GATEWAYNAME"]+'<->' +document["STARTTIMEDATETIME"]

                        document["GRANULARITYPERIOD"]=15

                        try:
                            data_time = familyObj.parseEnvelopeDataTime(data_time)
                        except ValueError as e:
                            logger.warning("Could not build mediationEnvelope due to {0}: ".format(e), __file__)
                            continue

                        # envelope
                        familyObj.addDocument({"dataTime": data_time, "granularitySec": 900, "data": document})
                        self.nextOp(familyObj=familyObj, baseObject=baseObject)
                        familyObj.clearDocuments()


            except csv.Error as e:
                logger.warning("{0} in line {1} of file {2}".format(e, n_line, file_name))



    def processEnrichFiles(self):
        endpoints = []
        # ordenar pelo mais recente
        for root, dirnames, filenames in sorted(os.walk('/opt/ptin/medrepo/synchronizedRepository/GENBAND/CFG/127.0.0.1'), reverse=True):
            for filename in sorted(fnmatch.filter(filenames, 'ENRICH*.csv'), reverse=True):
                filePath = os.path.join(root, filename)

                with open(filePath) as fp:
                    c = 1
                    for line in fp:
                        line = line.strip()
                        if line == 1:
                            tableName = line
                        elif line == 2:
                            dt = line
                        else:
                            if line not in endpoints:
                                endpoints.append(line)
                        c += 1

            # para so processar o ficheiro mais recente
            return endpoints
        # se nao encontrar ficheiros
        return None

    def enrichment(self, ingresstrunk, egresstrunk):
        callType=''

        if ingresstrunk in self.__endpoints and egresstrunk in self.__endpoints:
            callType="Incoming/Outgoing"

        elif ingresstrunk in self.__endpoints:
            callType= "Outgoing"

        elif egresstrunk in self.__endpoints:
            callType= "Incoming"

        return callType
