apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-ericsson-oss-ran-pm-2g-rjoapp1-apgfiles-sts
spec:
  schedule: 7,22,37,52 * * * *
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  timeZone: America/Sao_Paulo
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: 'true'
          labels:
            app.kubernetes.io/component: namf
            app.kubernetes.io/name: namf-sync
            tef-l3-service-network-access: 'true'
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: altaia-app/cronjob-access
                    operator: In
                    values:
                    - "true"
          topologySpreadConstraints:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: "namf-sync"
              maxSkew: 1
              topologyKey: "kubernetes.io/hostname"
              whenUnsatisfiable: ScheduleAnyway
          runtimeClassName: selinux
          serviceAccountName: altaia-namf-app-sa
          securityContext:
            fsGroup: 1982
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1982
            runAsUser: 1982
            supplementalGroups:
              - 1982
          containers:
            - name: sync-ericsson-oss-ran-pm-2g-rjoapp1-apgfiles-sts
              image: quay.apps.mgmt.tdigital-vivo.com.br/altaia_full/namf-public/namf/namf-sync:3.2.2-3.2-11453d54
              imagePullPolicy: IfNotPresent
              env:
                - name: TZ
                  value: America/Sao_Paulo
                - name: OPENSSL_ENABLE_SHA1_SIGNATURES
                  value: "1"
              command:
                - /bin/sh
                - -c
                - |
                  sleep 20; \
                  python3 /opt/alticelabs/namf/bin/na-mf-standalone-collect-python-sync/rsync-script.py \
                  /opt/alticelabs/namf/python/na-mf/collect/config/customization/ERICSSON_OSS_RAN_PM_2G_RJAPP1_APGFILES_STS_10.234.38.107.yml \
                  10.234.38.107 \
                  /var/opt/ericsson/sgw/outputfiles/apgfiles/sts \
                  /opt/alticelabs/namf/medrepo/staging/synchronizedRepository/ERICSSON/Performance2G \
                  $(date +'%Y%m%d') dbn0 --password=vIvo1234 \
                  --pingskip \
                  --statsreporting=MESSAGE \
                  --triggerparse
              volumeMounts:
                - name: configmap-namf-sync
                  mountPath: /opt/alticelabs/namf/python/na-mf/collect/config/logging.cfg
                  subPath: logging.cfg
                - name: configmap-namf-sync
                  mountPath: /opt/alticelabs/namf/python/na-mf/collect/config/customization/ERICSSON_OSS_RAN_PM_2G_RJAPP1_APGFILES_STS_10.234.38.107.yml
                  subPath: ERICSSON_OSS_RAN_PM_2G_RJAPP1_APGFILES_STS_10.234.38.107.yml
                - name: configmap-namf-sync
                  mountPath: /opt/alticelabs/namf/.ssh/config
                  subPath: ssh_config_older_crypto
                - name: storage
                  mountPath: /opt/alticelabs/namf/medrepo/staging
                - name: ssh-known-hosts
                  mountPath: /etc/ssh/ssh_known_hosts
                  subPath: ssh_known_hosts
                  readOnly: true
              resources:
                limits:
                  memory: 4096Mi
                  cpu: 1
                requests:
                  memory: 2048Mi
                  cpu: 0.2
          volumes:
            - name: configmap-namf-sync
              configMap:
                name: configmap-namf-sync
            - name: storage
              persistentVolumeClaim:
                claimName: namf-shared-filesystem
            - name: ssh-known-hosts
              secret:
                secretName: secret-namf-sync
                items:
                  - key: ssh_known_hosts
                    path: ssh_known_hosts
          restartPolicy: OnFailure
